### ISSUE TITLE
It doesn't notify added items.

### ISSUE THREAD

**Issue by adriasan** [RomainPierre7/jellyfin-plugin-TelegramNotifier#16]
Hello, I have a problem where all notifications are working correctly except for the one for added items.

I'm not sure if it's due to the file format since I use strm videos.
I repeat, all other notifications are sent without issue, but when I add new content, no message is sent.

And yes, I have checked that Jellyfin recognizes the series or movie and assigns the corresponding metadata

**Comment by RomainPierre7** [comment]
Hello,

That's weird. Did you check your logs when a new item is added ?

**Comment by Druidblack** [comment]
Good afternoon. If you are sure that you have configured everything correctly, but there are no notifications about adding new content. Try changing the time in the scheduler (from the user interface, you can select the minimum time of 15 minutes). I have encountered a problem when notifications did not arrive when adding new content. It turned out that this was due to the fact that the image (title image) did not have time to load (completely), and due to the peculiarity of the message being sent to telegram, he could not send text without an image and notifications were not sent.

Now, with a working time of 15 minutes, I receive all notifications.

**Comment by RunAway189** [comment]
Is it the expected behaviour to not have metadata and poster for added items tho? It'd be cool to have them. By the wat many thanks for your plugin @RomainPierre7

**Comment by RomainPierre7** [comment]
Hi @RunAway189, if an image is found in the metadata, it is displayed. Now the text will soon be customizable in a future update, and with the help of tags you'll be able to add any metadata you like within the message. Thank you for using the plugin and feel free to give it a star to help others discover it too ;)

**Comment by RunAway189** [comment]
@RomainPierre7 Sadly even if I have posters and metadata available they don't show up :(

**Comment by RomainPierre7** [comment]
@RunAway189  Can you send me an example of a notification ?

You should normally have something like:

![Screenshot_2024-12-04-15-41-00-12_948cd9899890cbd5c2798760b2b95377.jpg](https://github.com/user-attachments/assets/a027342c-985e-4298-b855-ad50d770c5f2)

**Comment by RunAway189** [comment]
It looks like this:
![Screenshot 2024-12-04 200234](https://github.com/user-attachments/assets/028a919a-4f7c-4131-bb45-616c12cbbf6d)

**Comment by RomainPierre7** [comment]
@RunAway189 As I said it is normal for metadata (if you meant like episode duration, etc), it will be implemented later.

Regarding the poster that's weird. Do you have it for some items or is it the same for every item ?

What did you set as your server IRL ? (don't answer your full IP address of course but just the "format")

Also did you check your logs ? (Ctrl + f "Telegram Added" and check the logs before and after in order to find more clues)

**Comment by RunAway189** [comment]
I've checked the logs and I got this:

[15:11:47] [INF] [282] Jellyfin.Plugin.TelegramNotifier.Plugin: Reaching for image: http://localhost:MYPORT/Items/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/Images/Primary
[15:11:47] [ERR] [295] Jellyfin.Plugin.TelegramNotifier.Plugin: (ItemAdded): Message could not be sent, please check your configuration.

It seems it fails to get the image but the notifications still work. Should I use my jellyfin remote domain? I'm also using NGIX PM

@RomainPierre7

**Comment by RunAway189** [comment]
> @RunAway189 and if you copy paste this url in your web browser from your local network. Do you get the image ?
> 
> Be just sure that in the url server setting you didn't add the "http" (so for example just "localhost:8096")

Tested and was not working, so I tried to put instead of localhost the IP address of my server and now I'm getting the poster!  🥳  Thanks a lot for your precious help, looking forward the next updates

**Comment by RomainPierre7** [comment]
Great news @RunAway189 ! Thanks to you for using the plugin and feel free to put a star on the project if you like it to allow more people to discover it. 

I'll be working on the next release very soon ;)

**Comment by RunAway189** [comment]
I'm sorry to re-open the discussion but I've noticed that even if the images are now working, the notifier tries to get them just once in a while, randomly. 

![Screenshot 2024-12-06 153124](https://github.com/user-attachments/assets/0218c928-1b2c-471c-b171-c070158c4de4)

**Comment by RomainPierre7** [comment]
What do you mean by randomly ? Image notifications are only enabled for seasons and series.

But for episode playback you will have the images.

**Comment by RunAway189** [comment]
> What do you mean by randomly ? Image notifications are only enabled for seasons and series.
> 
> But for episode playback you will have the images.

Sorry my bad, so it's intended to not having poster for episodes. Thanks :)

**Comment by RomainPierre7** [comment]
You're welcome ;)
