### ISSUE TITLE
Multiple configurations

### ISSUE THREAD

**Issue by LodeliKT** [RomainPierre7/jellyfin-plugin-TelegramNotifier#19]
I need two different kind of notifications:
1. An admin/management one to notify me when a playback starts or when a user is created
2. A more common, user-wise, one to notify a chat group when an item is added

In the effort of trying to return to Jellyfin after my Plex/Tautulli experience, I've just installed the plugin but can't find how to achieve these goals.

(Also, for point 1 would be useful to know if transcoding or not but it should be a different issue and I can live without this)

**Comment by RomainPierre7** [comment]
First of all, hello.

In your case, the easiest thing would be to install a second instance of the plugin. However, I don't know if this is easy to do.

**Comment by Lodeli** [comment]
Hello RomainPierre7 and really thank you for your really quick response.

I see; maybe this could be a future enhancement?
Or is it a little too of a refactor to implement it?

I don't know how useful this feature could be to others anyway...

**Comment by RomainPierre7** [comment]
I'll look into the possibility of doing this easily. But I can't guarantee anything, as the current format allows you to customize the notifications activated for each user separately. Which is already convenient for a lot of use cases.

**Comment by RomainPierre7** [comment]
Yes you can. The only constraint is to be on the same telegram bot. For example I have all the events enabled for my user (so I can see who is connecting, who is streaming, etc). And my family's users only have  the new item notifier enabled.

**Comment by Lodeli** [comment]
Ok, thank you again for your kindness.

There is still one thing I don't get.
I can set different bot_token and different chat_id for each user; this seems already as a sort of multiple configurations setup.
What's the meaning of selecting a user?

**Comment by RomainPierre7** [comment]
Hi @Lodeli, sorry, my message was confusing. I've edited it. You're right, you can already configure the bot independently for each user, so it's very handy if you want everyone to be on the same bot or not ;)

**Comment by Lodeli** [comment]
Great, I think this fulfill perfectly what I need.

Just to clear my last doubt: why the per-user configuration?
If you removed the dropdown with the users and use instead a dynamic list wouldn't it be the same?

I don't know if I'm able to fully explain what I mean.
For example, let's say you have 5 users: now you can create 5 individual configurations and the selected user seems to not have any meaning (to me, but this is what I'm missing).
If this multiplicity of configurations was bound to some dynamic list of "simple strings" (just configuration names), instead of the users list, you could have as many configurations as you want.

**Comment by RomainPierre7** [comment]
Hi,

It could be useful for the "not notify my own activities" option. But you are right except that the config is not really linked to the user. I did this because normally you want a config per user.
