### ISSUE TITLE
Add telegram thread id to send messages on a specifict thread

### ISSUE THREAD

**Issue by Tresillo2017** [RomainPierre7/jellyfin-plugin-TelegramNotifier#7]
For those who use a telegram channel with multiple threads including the option to add a thread id to send messages inside that thread would be nice

**Comment by RomainPierre7** [comment]
I'll plan to work on it ;)

**Comment by RomainPierre7** [comment]
The update is available ([release](https://github.com/RomainPierre7/jellyfin-plugin-TelegramNotifier/releases/tag/10.9.10.0)), and you can now fill the thread id option to fit your need. Your server will update within 24 hours, but you can force it from Dashboard => Scheduled tasks => Update plugins.

Thanks to feedback and if you're finding value in this project and it's been helpful to you, consider giving it a star ⭐️ on GitHub !

**Comment by hdjin7** [comment]
Hello @RomainPierre7, first of all, thank you very much for your amazing community plugin.

In the (default) method of installing the plugin directly through Jellyfin, the new version 10.9.10.0 is not showing up to be installed/updated (as you can see in the screenshot, and there is the date there in the corner to confirm that it is really not showing up).

![TelegramNotifierVersion](https://github.com/user-attachments/assets/cdeb9407-5bde-467d-9a2e-cc263a20d293)

I downloaded the zip of version 10.9.10.0 and changed the current dll in the Jellyfin plugins folder. I also edited the meta.json correctly to version 10.9.10.0, but it didn't work, because the plugin settings option doesn't show up (my Jellyfin runs on Docker on Ubuntu server).

Does it really take a while for this new version to show up in Jellyfin? Or is there really an error occurring in the deployment that is not showing up?

I'm really looking forward to using the message_thread_id option in the new version 10.9.10.0

(note: I'm writing this here because the discussions option doesn't appear in the TelegramNotifier repository)

Thanks again for your work. :)

**Comment by RomainPierre7** [comment]
Hi, I'm glad you found this plugin useful. Thank you very much!

Personally, I managed to install the new version via the default installation. And the advantage is that you'll be able to get future updates. So let's try this first.

I'm pretty sure it's because you don't have the latest version of the Jellyfin server (≥10.9.10). But nevermind I just changed the [manifest](https://raw.githubusercontent.com/RomainPierre7/jellyfin-plugin-TelegramNotifier/main/manifest.json) to be less strict so ≥10.9.4 would work. Try again and let me know.

If it really doesn't work and you want to install it manually, retrieve your important settings like Bot token, Chat Id, etc and delete the TelegramNotifier folder under plugin and its configuration in configuration. Then restart the server and check that the plugin is deleted in the Jellyfin web interface in your plugins. Then create a new TelegramNotifier folder under the plugin folder. Place the new dll inside and restart. You should then be able to see the plugin options, so all you have to do is configure the plugin again and have fun ;)

**Comment by hdjin7** [comment]
Thank you very much for responding @RomainPierre7 :)

Yes, I was using Jellyfin version 10.9.9, I forgot to mention that (even though it was set to lastest, for some reason CasaOS did not automatically update JF to version 10.9.10).

I was able to install it directly through the standard Jellyfin installation (before installing it, I turned off JF, deleted the plugin folder and its xml file in the configuration subfolder in the plugins folder to eliminate possible conflicts, turned on JF and installed version 10.9.10 of its plugin).

I configured everything (BotToken, chatId and threadId, etc.), with the threadId provided, I ran the 'test bot configuration' and everything went well, responding with the test message in the Telegram group topic correctly.

I added a new movie, tracked the library and the plugin did not notify me automatically on Telegram. I went to tasks and ran the plugin manually a few times. Sometimes it said that the task 'failed' and other times it seemed normal, as if the task had been executed correctly. However, in both cases the plugin did not notify me on Telegram (I did these tests by removing the movie, updating the library, adding the movie again and updating the library again, and running the task again. I also restarted JF a few times to see if it resolved the issue).

I also tested by trying to leave the threadId empty (and doing the same tracking and task tests, and the result was the same). In the case where the threadId was not informed, when I did the 'test bot configuration', it returned 'test failed' and the test message was not sent to Telegram.

I looked at the logs and it shows when the task fails, and when the task is "successful" (as I said before, only "success" appears, but the plugin does not actually send the notification to Telegram).
![logs](https://github.com/user-attachments/assets/07d1611f-f7e6-48eb-a58d-323217cac91a)

I debugged using the Edge/Firefox browser (with and without the threadId informed), and I noticed that even with the threadId informed and the 'test bot configuration' sending the notification correctly to the topic (as you can see in the corner of the print), the debug shows the "ThreadId" variable empty when the test/task runs (in both cases, with and without the threadId informed).
![debug](https://github.com/user-attachments/assets/7294c351-4b81-4edc-a85a-169d83d817f4)
![testBotThreadIdInsert](https://github.com/user-attachments/assets/7d4b1e7a-2bdc-418b-9783-41f67a5d2109)

Another thing I noticed (it may have nothing to do with it, but it's worth mentioning), is that in its manifest the new version 10.9.10 of the plugin also has the "targetAbi": "10.9.4.0" of the previous version.
![manifest](https://github.com/user-attachments/assets/d8bdb789-510b-4805-8dab-5db1bba78028)

I also updated JF to the latest version 10.9.10 (again I did a clean installation of the plugin without any old files/folders) and ran all the previous tests/debugs again with the latest version of JF and got the same results. With that I went back to the previous version 10.9.4 of the plugin (which is working normally) so that I wouldn't lose the notifications on Telegram.

I don't know if this problem is just me or if the plugin really has a bug, but I believe it's the latest version of the plugin, because I tested TN v10.9.4 on the previous and current versions of JF and both had the same problem, and with TN v10.9.4 it works correctly on both versions of JF.

**Comment by RomainPierre7** [comment]
Hello again. The fix is released ([10.9.10.1](https://github.com/RomainPierre7/jellyfin-plugin-TelegramNotifier/releases/tag/10.9.10.1)). Thanks for reporting the bug ;) That was a typo. Don't hesitate to reach me again if you notice something else !
